### ISSUE TITLE
Tracking individual packages

### ISSUE THREAD

**Issue by ido1990** [bachya/py17track#12]
Hi,
Is it possible to use it for tracking individual packages?
Found your work after looking for 17track api.
I saw you also made a plugin for HomeAssistant.

When I tried to reverse engineer the api I found that they use cookie for each track made on the website.

Looking for some leads on the topic.

Thanks!

**Comment by bachya** [comment]
Thanks for reaching out!

Once upon a time, there was a reverse-engineered way to track individual packages (see https://github.com/bachya/py17track/blob/dev/py17track/track.py). Unfortunately, 17track.net has introduced some sort of key into the header of these calls on their site; to date, I've not discovered a way to reproduce the value of that header. Without it, the responses fail.

It sounds like this is the same thing you're running into:

>When I tried to reverse engineer the api I found that they use cookie for each track made on the website.

So, I think we're stuck for the moment. Feel free to use the code in [`track.py`](https://github.com/bachya/py17track/blob/dev/py17track/track.py) as an investigation starting point; perhaps you will have more luck than I (and if you do, please post back here).

**Comment by ido1990** [comment]
Thank you!
I couldn't find any way yet how to bypass that cookie system.
The only way I think of is using using some kind of headless browser to actually create the cookie for the first time.
I found this one:
https://rapidapi.com/apidojo/api/17track
But I'm no sure how he did it.

**Comment by bachya** [comment]
Got it! Interesting to consider. One note: if you do end up going that route, we won't be able to use it in Home Assistant (see https://github.com/home-assistant/architecture/blob/master/adr/0004-webscraping.md) – may not be a big deal, but something to keep in mind.
