### ISSUE TITLE
Package location often in different field of json response

### ISSUE THREAD

**Issue by jdonley** [bachya/py17track#48]
**Describe the bug**
The package location is often returned in the field named "d" in the json response. Currently the field named "c" is used and is often (always?) empty.

**To Reproduce**
Observe missing 'location' data.

**Expected behavior**
Location should be assigned from the non-empty value that contains the location string.

**Screenshots**
n/a

**Additional context**
Replace [line 79 of profile.py](https://github.com/bachya/py17track/blob/5efff0e078d653441b2f1b13fa6d18830b1f2798/py17track/profile.py#L79) with:
`"location": event.get("c" if event.get("c") != '' else "d"),`

**Comment by bachya** [comment]
Since you understand the code change, how about a PR?
