### ISSUE TITLE
Feature: add tracking number

### ISSUE THREAD

**Issue by ofalvai** [bachya/py17track#53]
Is there any reason why adding a tracking number to the user's profile is not implemented yet? I think it would be cool to have a Home Assistant service for that.

I looked at the API calls in the background, and adding a tracking number calls `https://buyer.17track.net/orderapi/call` with this payload:

```json
{
    "version": "1.0",
    "timeZoneOffset": -60,
    "method": "AddTrackNo",
    "param": {
        "TrackNos": [
            "123456789"
        ]
    }
}
```

If this feature makes sense, I would be happy to open a PR.

**Comment by bachya** [comment]
@ofalvai Please! Appreciate the help.
