### ISSUE TITLE
Just a general quick fix

### ISSUE THREAD

**Issue by nicholasyoannou** [bachya/py17track#58]
**Describe the bug**
In the about me of this github, it says 17track.COM but it is now 17track.NET.

**To Reproduce**
1. Go to the code tab on this github
2. Look at about me
3. See that it says .com instead of .NET

Just a general quick fix, wanted to mention.

**Comment by bachya** [comment]
I'm not seeing this – everywhere in the README shows "17track.net". Can you be more specific?￼
