### ISSUE TITLE
Force package status refresh on fetch

### ISSUE THREAD

**Issue by aneisch** [bachya/py17track#7]
**Is your feature request related to a problem? Please describe.**
When I initiate a session and grab a list of my deliveries their status doesn't update (unless 17track has some interval on their backend that I haven't noticed)

**Describe the solution you'd like**
I'd like if the delivery status update would be forced for my packages when I initiate a session. If I open the Android app and pull down to refresh, the next time I run a `packages = await client.profile.packages()` I see the updated status.

**Comment by bachya** [comment]
When you say your deliveries' status "doesn't update", do you mean that if you call `await client.profile.packages()` again after creating a client, you see old data?

**Comment by andrew-smartcash** [comment]
Correct, but let me clarify, `profile.packages` gets an updated list of my packages, but does not seem to trigger an update of their status.

**Comment by aneisch** [comment]
Correct, but let me clarify, `profile.packages` gets an updated list of my packages, but does not seem to trigger an update of their status.

**Comment by bachya** [comment]
I am not experiencing this, unfortunately. Will continue to investigate.

**Comment by aneisch** [comment]
I've been paying closer attention and at this point I'm not convinced it is an issue here actually. Specifically for USPS packages, 17track seems to have a significant delay in showing the same status as usps.com tracking. This could just be a limitation of USPS API or maybe 17track is rate limiting themselves querying USPS for status.

**Comment by bachya** [comment]
Got it – thanks for the follow up. Let’s close this for now; if you find further evidence that there’s a bug in this package, we can absolutely reopen it. Thanks!
