### ISSUE TITLE
Support new API?

### ISSUE THREAD

**Issue by jmswindle** [bachya/py17track#72]
**Is your feature request related to a problem? Please describe.**
17Track has a new API that utilizes tokens instead of username/password: https://api.17track.net/en/doc

**Describe the solution you'd like**
Are there plans to migrate to this new API? I'd be happy to help out where I can.

**Additional context**
I recently switched to 17track from aftership in my HomeAssistant configuration and noticed some lacking features - like adding and removing tracking numbers from HASS. I started looking at the APIs and saw they were available, but not implemented.
I was gonna work on implementing them myself, but wasn't sure if it was already in development.

**Comment by bachya** [comment]
@jmswindle Thanks for your request! I actually no longer have the bandwidth to maintain this library, so if somebody wanted to take it over, I would be happy to transition. Interested?

**Comment by jmswindle** [comment]
@bachya yea, I suppose I could take over, I'll have to dust off my python skills a bit

**Comment by bachya** [comment]
Chew on it! If you're still interested, let me know and we can plan.

**Comment by ahasbini** [comment]
I stumbled upon this and tried out the new [https://api.17track.net](https://api.17track.net/en/doc).

Firstly, there's a v2 of the API. The docs say it's better than v1 in terms of tracking statuses and time conversion.

Secondly, there's a bit of a confusion/problem with accounts on 17track. I had an account on 17track, tried to open the api docs but constantly got the error page "permission denied", even though I was able to access [https://buyer.17track.net/](https://buyer.17track.net/). Then I created a new a account on 17track by signing up as a developer (with a different email) which worked and I was able to get my access token, however I can't open [https://buyer.17track.net/](https://buyer.17track.net/) anymore. So in summary, if a person already has a "buyer" account then that person can't use the APIs, and if a person has "developer" account then that person can't access [https://buyer.17track.net/](https://buyer.17track.net/), which might be confusing to some (for example for people that have 17Track app on their phones).

Lastly, there is a 100 tracking numbers per month quota in the free plan.
